# Generated by Django 4.2.7 on 2023-12-13 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='source',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='quote',
            name='context',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AlterField(
            model_name='quote',
            name='quote_author',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='quote',
            name='quote_body',
            field=models.TextField(),
        ),
    ]
